### ISSUE TITLE
package is not working well in mac 

### ISSUE THREAD

**Issue by sahyagiri** [smc/mlmorph#8]
Gives blank. 
<img width="1132" alt="Screenshot 2020-03-01 at 8 35 54 PM" src="https://user-images.githubusercontent.com/8480235/75628159-643fa400-5bfc-11ea-84cc-aeac35372df4.png">

<img width="1620" alt="Screenshot 2020-03-01 at 9 33 53 PM" src="https://user-images.githubusercontent.com/8480235/75629016-76bddb80-5c04-11ea-8bf1-c4d74f9a4437.png">

UPDATE: Not working in Colab as well

**Comment by sahyagiri** [comment]
Update: Made it working with single word. Multi-word string is returning null 
<img width="688" alt="Screenshot 2020-03-03 at 10 31 45 PM" src="https://user-images.githubusercontent.com/8480235/75799918-cf28e080-5d9e-11ea-805f-7670b591c7bb.png">

**Comment by santhoshtr** [comment]
The analyse method takes only a compound word. Splitting the sentense should be done outside. Refer the python code in tests folder for samples.
